//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATeam.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://examplanner.pgs-soft.com/ateam")]
        public string StartUrl {
            get {
                return ((string)(this["StartUrl"]));
            }
            set {
                this["StartUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ateam1@pgs-soft.com")]
        public string UserAteam1 {
            get {
                return ((string)(this["UserAteam1"]));
            }
            set {
                this["UserAteam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YhBQWmtQLt")]
        public string PasswordAteam1 {
            get {
                return ((string)(this["PasswordAteam1"]));
            }
            set {
                this["PasswordAteam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ateam2@pgs-soft.com")]
        public string UserAteam2 {
            get {
                return ((string)(this["UserAteam2"]));
            }
            set {
                this["UserAteam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MTd4QHdI8i")]
        public string PasswordAteam2 {
            get {
                return ((string)(this["PasswordAteam2"]));
            }
            set {
                this["PasswordAteam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ateam3@pgs-soft.com")]
        public string UserAteam3 {
            get {
                return ((string)(this["UserAteam3"]));
            }
            set {
                this["UserAteam3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4dR5NU7eUJ")]
        public string PasswordAteam3 {
            get {
                return ((string)(this["PasswordAteam3"]));
            }
            set {
                this["PasswordAteam3"] = value;
            }
        }
    }
}
